### ISSUE TITLE
IDBBatchAtomicVFS error: `TypeError: Cannot read properties of null (reading 'fileSize')`

### ISSUE THREAD

**Issue by thanhnguyen2187** [rhashimoto/wa-sqlite#137]
Hi!

Thanks for the awesome library. I'm toying around with it to make a "full-stack" SQLite web application (SQLite persistence in browser and SQLite in the server). However, I encountered a strange error, trying to make `IDBBatchAtomicVFS` works. My code is something like this:

```typescript
import * as IDBBatchAtomicModule from 'wa-sqlite/src/examples/IDBBatchAtomicVFS.js'

export async function hello() {
  const module = await SQLiteESMFactory()
  const sqlite3 = SQLite.Factory(module)
  const vfs = new IDBBatchAtomicModule['IDBBatchAtomicVFS']([])
  await vfs.isReady
  sqlite3.vfs_register(vfs, true)
  const db = await sqlite3.open_v2('mydb')
  const queryContent = (await import('../../../queries/01__snippet_creation.sql?raw')).default
  await sqlite3.exec(
    db,
    queryContent,
  )
  await sqlite3.close(db);
}
```

Where `queryContent` is something like:

```sql
CREATE TABLE IF NOT EXISTS snippets (
    id TEXT PRIMARY KEY,
    "name" TEXT,
    "language" TEXT,
    "text" TEXT,
    "encrypted" BOOLEAN,
    position REAL,
    updated_at DATETIME,
    created_at DATETIME
);
```

The error is like this:

```
TypeError: Cannot read properties of null (reading 'fileSize')
    at #xWriteHelper (IDBBatchAtomicVFS.js:247:40)
    at IDBBatchAtomicVFS.xWrite (IDBBatchAtomicVFS.js:232:17)
    at Ic (wa-sqlite.mjs?url:70:51)
    at wa-sqlite.wasm:0x70b37
    at wa-sqlite.wasm:0x57d2c
    at wa-sqlite.wasm:0x57ecf
    at wa-sqlite.wasm:0x2329
    at wa-sqlite.wasm:0x3f6f0
    at wa-sqlite.wasm:0x15241
    at wa-sqlite.wasm:0x5f3f7
```

Do you have any idea how does this error happen and what can I do to fix it? I'm using Vite, installing the library from GitHub with `yarn install rhashimoto/wa-sqlite`, but still serving the `.mjs` and `.wasm` files as static files.

Many thanks!

**Comment by thanhnguyen2187** [comment]
For full reproducibility, you can checkout this branch of my code (https://github.com/thanhnguyen2187/crypta/pull/28), then do `yarn install`, `yarn dev`, and look at the console log.

**Comment by thanhnguyen2187** [comment]
Oh I see. That really make sense. I changed the importing to `wa-sqlite-async.mjs` and it worked. Many thanks for your help!

Maybe a document on how to use the example VFS would be really helpful. What do you think?

**Comment by rhashimoto** [comment]
There is [this entry](https://github.com/rhashimoto/wa-sqlite/issues/15) in the FAQ, and sample application code under [demo/](https://github.com/rhashimoto/wa-sqlite/tree/master/demo). It might be good to add a hello-async demo.
