### ISSUE TITLE
Strange error stack trace: both "SQL error" and "journal file not found"

### ISSUE THREAD

**Issue by thanhnguyen2187** [rhashimoto/wa-sqlite#139]
Hi. I encountered these strange stack trace on using `wa-sqlite` in my project:

![image](https://github.com/rhashimoto/wa-sqlite/assets/27758849/f7d8597b-c3e3-4eb6-a4ce-6587072708c9)

Upon reproducing/figuring out how does the error happen, it looks like at that moment, there seems to be two place "simultaneously" call  `wa-sqlite`:

```typescript
// in one file
  onMount(async () => {
    await migrate(localDb, defaultMigrationQueryMap, defaultQueriesStringMap)
  })

// in another
export const localSnippetsStore = await createLocalSnippetStoreV2(localDb)
```

Where `localDb` is a wrapper of Drizzle around `SQLiteAPI` that uses `.statements`:

```typescript
// in one file
export async function createLocalDb(executor: QueryExecutor) {
  return drizzle(async (queryString, params, method) => {
    const result = await executor.execute(queryString, ...params)
    if (method === 'get' && result.length > 0) {
      return {rows: result[0]}
    }
    return {rows: result}
  })
}

// in another
    ...
    async execute(query: string, ...params: SQLiteCompatibleType[]): Promise<SQLiteCompatibleType[][]> {
      const rows = []
      for await (const stmt of sqlite3.statements(db, query)) {
        params.forEach((param, index) => sqlite3.bind(stmt, index + 1, param))
        while (await sqlite3.step(stmt) === SQLite.SQLITE_ROW) {
          rows.push(sqlite3.row(stmt))
        }
      }
      return rows
    },
    ...
```

If I comment out the `await migrate` and only run `localSnippetStore = ...` (or vice versa), then the code works as expected. Therefore, I feel like my way of wrapping might be the problem, but cannot be sure how to process further. Do you have any suggestion?

Many thanks!

**Comment by thanhnguyen2187** [comment]
I only mention code snippets that I feel important to `wa-sqlite`. You are free to check out the full code here: https://github.com/thanhnguyen2187/crypta/pull/28.

**Comment by rhashimoto** [comment]
I agree that you're likely overlapping calls into wa-sqlite. That's on you to debug, I'm afraid. You might try setting a breakpoint on each API call you make to check the state of your application.

**Comment by rhashimoto** [comment]
You could also try using the debug build. You would need to follow the build instructions from the [README.md](https://github.com/rhashimoto/wa-sqlite/blob/master/README.md) and `make debug`, which writes the WASM artifacts to debug/ (instead of dist/). That might assert sooner and/or give you more actionable error messages.

**Comment by thanhnguyen2187** [comment]
Thanks a lot for the suggestion! I thought of another way to mitigate the issue and was going to work on it soon, but I'll also try the debugging WASM and let you know if there is anything relevant.

Another question: theoretically, `wa-sqlite` (and `IDBatchAtomicVFS`) should be able handle concurrent reads, and mixed reading writing, right? I rechecked my code and there were two cases:

- One read, one write
- Two reads

Unless they are concurrent writes, I feel like `wa-sqlite` should be able to handle those cases.

**Comment by rhashimoto** [comment]
> theoretically, wa-sqlite (and IDBatchAtomicVFS) should be able handle concurrent reads, and mixed reading writing, right?

If you mean on the same instantiated WASM module, no. You cannot have multiple calls to SQLite in flight simultaneously.

If you mean concurrent transactions on the same database from different instantiated WASM modules (typically also from different JavaScript contexts), whether you can overlap transactions depends on locking support in the VFS you use. See [this FAQ item](https://github.com/rhashimoto/wa-sqlite/issues/5) for details.

**Comment by thanhnguyen2187** [comment]
> If you mean on the same instantiated WASM module, no. You cannot have multiple calls to SQLite in flight simultaneously.

I see. Everything makes sense now. I'll elaborate the case for posterity.

There is this piece in my code:

```typescript
export async function createSQLiteAPI(): Promise<SQLiteAPI> {
  // @ts-ignore
  const module = await SQLiteESMFactory()
  const sqlite3 = SQLite.Factory(module)
  const vfs = new IDBBatchAtomicVFS()
  // const vfs = new OriginPrivateFileSystemVFS()
  sqlite3.vfs_register(vfs, true)
  return sqlite3
}
```

Where the returned result is used in another object. That object is utilized in two different places simultaneously (as per the first comment). In the end, it raises some seemingly unrelated stack traces like the first comment.

**Comment by abhay-agarwal** [comment]
What if you set up a pool of connections within a shared worker, and then accessed each of those connections using different locks? Or a hierarchical locking strategy?
