### ISSUE TITLE
Error: no such module: rtree

### ISSUE THREAD

**Issue by jmatsushita** [rhashimoto/wa-sqlite#149]
I'm trying to use the [rtree module following the sqlite docs](https://www.sqlite.org/rtree.html) however this statement fails:

```sql
CREATE VIRTUAL TABLE demo_index USING rtree(
   id,              -- Integer primary key
   minX, maxX,      -- Minimum and maximum X coordinate
   minY, maxY       -- Minimum and maximum Y coordinate
);
```

with this error:
```
Error: no such module: rtree
    at check (https://rhashimoto.github.io/wa-sqlite/src/sqlite-api.js:857:11)
    at Object.step (https://rhashimoto.github.io/wa-sqlite/src/sqlite-api.js:690:14)
    at async execute (https://rhashimoto.github.io/wa-sqlite/src/examples/tag.js:50:16)
```

I've checked by doing a local build that `-DSQLITE_ENABLE_RTREE` is indeed passed as a compilation option, so I would expect this to work. Unless I'm missing something?

Cheers,

Jun

**Comment by rhashimoto** [comment]
I'm pretty sure rtree is not enabled in my builds. If you try `PRAGMA compile_options` in the demo, there's no `ENABLE_RTREE`. There are some suggestions for customizing your own build [here](https://github.com/rhashimoto/wa-sqlite/discussions/128).

**Comment by jmatsushita** [comment]
Perfect thank you `make WASQLITE_EXTRA_DEFINES="-DSQLITE_ENABLE_RTREE"` did the trick!
