### ISSUE TITLE
Empty blobs as bind parameters being returned as NULLs

### ISSUE THREAD

**Issue by msfstef** [rhashimoto/wa-sqlite#168]
Currently empty blobs can be written and read unless they are inserted as bind parameters, in which case they get returned as `null`. Issue seems to be that nothing gets allocated for them and are interpreted as NULLs.

PR with suggested fix: https://github.com/rhashimoto/wa-sqlite/pull/167

**Comment by sgbeal** [comment]
That's how the C library works: <https://sqlite.org/c3ref/column_blob.html> returns a C NULL for length-zero blobs, and C NULL is interpreted as SQL NULL except in cases where a C NULL is interpreted as an allocation error.

**Comment by rhashimoto** [comment]
There's additional relevant discussion in the [PR](https://github.com/rhashimoto/wa-sqlite/pull/167). Summary: this behavior by the C library is less than ideal but altering that behavior in a wrapper API is also not ideal. There's no everyone wins solution here, unfortunately.
