### ISSUE TITLE
OPFSAdaptiveVFS: "unreachable" error

### ISSUE THREAD

**Issue by sampbarrow** [rhashimoto/wa-sqlite#228]
Getting this error randomly on queries. "RuntimeError: Aborted(RuntimeError: unreachable). Build with -sASSERTIONS for more info."

```
wa-sqlite-async.mjs?v=4426c020:9 Uncaught (in promise) RuntimeError: Aborted(RuntimeError: unreachable). Build with -sASSERTIONS for more info.
    at abort (wa-sqlite-async.mjs?v=4426c020:9:4194)
    at runAndAbortIfError (wa-sqlite-async.mjs?v=4426c020:9:71943)
    at wa-sqlite-async.mjs?v=4426c020:9:75241
```

**Comment by rhashimoto** [comment]
This isn't enough information here to be actionable for me. Can you perhaps log your SQL and distill a reproducible test case? Or if that isn't feasible try running with a debug build - follow the [build instructions](https://github.com/rhashimoto/wa-sqlite?tab=readme-ov-file#build) and `make debug` will put artifacts into debug/ or you can download [this](https://github.com/user-attachments/files/18012613/wa-sqlite-debug.tgz) - and see if the error message is more informative.

Whatever you do, you need to provide more details on what you're doing, e.g. what browsers show the problem, what wa-sqlite version, whether there are multiple active connections, what kinds of queries fail, do subsequent queries succeed, does it happen with a different VFS, etc. "Happens randomly" isn't much for me to work with.

**Comment by sampbarrow** [comment]
Yes sorry I wasn't sure if this error was meaningful at all and thought there might be something obvious I could do to test further.

So I did figure out that if I mutex all calls to my query method that seems to fix it - so I assume it has something to do with my query method being called in parallel and since it's a multi step process (preparing the statement, fetching the rows, etc) the steps from multiple queries were overlapping. With the mutex it works great.

Is this expected behavior? If not I will follow those debug steps and/or try to put together an isolated test case to reproduce this.

To answer what I can for now, subsequent queries did fail after the error, it was specific to this vfs (also tried coop and idbbatchatomic), I am using Chrome 123.0.6312.105 on Arch, for version I am just using the main branch of this repo as of yesterday.

Great job on this VFS by the way. Stable, performance is great, handles multiple tabs well, and using this I can get rid of all of the application level complexity of coordinating multiple connections using sqlite's official access handle pool build which has really been a thorn in my side.

Probably not necessary but my query method for reference:

```
async function exec(api: SQLiteAPI, connection: number, sql: string, parameters?: readonly unknown[] | undefined) {
    const statements = await Array.fromAsync(api.statements(connection, sql, { unscoped: true }))
    try {
        const first = statements.at(0)
        if (first === undefined) {
            throw new Error("No statements in SQL.")
        }
        api.bind_collection(first, (parameters ?? []) as SQLiteCompatibleType[])
        const columns = api.column_names(first)
        const rows = new Array<readonly SQLiteCompatibleType[]>()
        while (await api.step(first) === SQLite.SQLITE_ROW) {
            rows.push(api.row(first))
        }
        return [
            {
                columns,
                rows,
            }
        ]
    }
    finally {
        statements.forEach(statement => {
            api.finalize(statement)
        })
    }
}
```

**Comment by rhashimoto** [comment]
> So I did figure out that if I mutex all calls to my query method that seems to fix it - so I assume it has something to do with my query method being called in parallel and since it's a multi step process (preparing the statement, fetching the rows, etc) the steps from multiple queries were overlapping. With the mutex it works great.
> 
> Is this expected behavior?

Calls to the SQLite API should not be overlapping so I do expect some kind of bad behavior. I'm not sure what specific bad behavior can occur but the one you report is certainly plausible. My guess is your diagnosis and fix are correct.

Regarding your query code, it would be simpler to use a for-await loop with a scoped `statements()` call to manage the prepared statement lifetimes implicitly, but perhaps you just wanted to practice with unscoped prepared statements. I think your code is not quite correct - if your SQL contains multiple statements with the first 1+ preparing successfully but preparing a later statement throws, then you will leak the earlier ones.

You call `column_names()` before calling `step()`. This usually works, and perhaps will always work in your particular application, but the names can be wrong for a `SELECT *...` if another connection modifies the schema, as discussed [here](https://sqlite.org/forum/info/7774b773937cbe0a). Even if it is safe in the current context, code might be copy-pasted into a different context in the future, so either fixing it or commenting it might be prudent.

**Comment by sampbarrow** [comment]
Got it. With the mutex I can not make it fail with that error no matter what I do so seems like a safe bet that was it. Will close this issue.

And thanks for pointing out the column_names thing, would not have caught that otherwise.
