### ISSUE TITLE
Publish as npm module

### ISSUE THREAD

**Issue by delaneyj** [rhashimoto/wa-sqlite#39]
Very curious in your approach, wanted it to be directly from npm... especially given the GPL licensing.  In the mean time I'll try building locally.

**Comment by rhashimoto** [comment]
Please see https://github.com/rhashimoto/wa-sqlite/issues/12

You can avoid building by fetching the [buildless](https://github.com/rhashimoto/wa-sqlite/tree/buildless) branch.

**Comment by delaneyj** [comment]
My apoligies
