### ISSUE TITLE
xSync should commit all xWrite things to the Indexed DB?

### ISSUE THREAD

**Issue by zzyhdu** [rhashimoto/wa-sqlite#53]
https://github.com/rhashimoto/wa-sqlite/blob/29a38da3dc001f8e6844837f6f3dffcdda2cdb10/src/examples/IDBContext.js#L97

 I'm someone new with Sqlite. But what i'm think is: when sqlite call the xSync, we may need to flush all thing to the disk(Indexed DB).Like:

  async sync() {
    await #chain;
    return this.#txComplete;
  }

Correct me if i have something misunderstand.

**Comment by rhashimoto** [comment]
The `IDBContext.sync()` implementation waits for any pending request to complete and then returns a Promise that resolves when the current transaction is complete. I think that does exactly what you're saying. Can you provide an example sequence of events where this fails?

**Comment by zzyhdu** [comment]
Sorry about the long time reply. Just back from hospital. Rerun the code, it went well. I will close the issue. Sorry again~ aha
