### ISSUE TITLE
BigInt support

### ISSUE THREAD

**Issue by tantaman** [rhashimoto/wa-sqlite#66]
Passing BigInt to the bind APIs currently converts them to null as their type is not handled in the switch statement.

https://github.com/rhashimoto/wa-sqlite/blob/4c5fd0e4afd9eb1dadbd621a41db4916fe47ed67/src/sqlite-api.js#L71-L90

Looking at the official WASM build -- looks like it is possible to just expose `bind_int64` from the C api and pass a BigInt to it.

**Comment by sgbeal** [comment]
> Looking at the official WASM build -- looks like it is possible to just expose bind_int64 from the C api and pass a BigInt to it.

Only if the wasm file is built with that support using Emscripten's `-sWASM_BIGINT` flag or the equivalent (if any) for other build environments. If you try to invoke wasm-exported int64 results/arguments without that flag, a black hole opens and sucks all things into it (or something like that - it's been half a year since i tried it).

**Comment by tantaman** [comment]
I fixed this in my fork. If you like, I can rebase the commits onto main (removing unrelated changes specific to my use case) and send over a clean PR.

Preview of said fix:
https://github.com/vlcn-io/wa-sqlite/pull/1

**Comment by rhashimoto** [comment]
I'm generally [not accepting pull requests](https://github.com/rhashimoto/wa-sqlite/blob/master/.github/pull_request_template.md), so probably not worth bothering to make a clean PR. I'll likely take a look at your fork, though, when you get it working.

**Comment by rhashimoto** [comment]
I believe we can avoid using WASM_BIGINT and just use legalization. That would limit changes to where they are actually needed and prevent unnecessary conversions to BigInt and back. The [documentation](https://emscripten.org/docs/getting_started/FAQ.html#how-do-i-pass-int64-t-and-uint64-t-values-from-js-into-wasm-functions) describes how to pass int64 arguments from Javascript to WASM and how to get int64 return values from WASM to Javascript. We'll see if I can escape the black hole.

* Add:
   * bind_int64
   * column_int64
   * result_int64
   * value_int64
* Modify convenience functions:
   * bind
   * column
   * result
   * value 
* Test:
   * 64-bit values go into and come out of SQLite (as BigInt)
   * 64-bit arithmetic works within SQLite
   * convenience functions recognize and return BigInt values (including bind_collection)

**Comment by rhashimoto** [comment]
Getting started on this. Legalization seems to be working for me in both directions - receiving int64 as return values from SQLite, and passing int64 as arguments to SQLite. The only tricky part so far has been assembling a 64-bit BigInt from a pair of 32-bit Numbers (mainly handling the low word sign bit).
