### ISSUE TITLE
mjs and masm files ( /dist) are missing

### ISSUE THREAD

**Issue by jalsco** [rhashimoto/wa-sqlite#70]
Hi @rhashimoto  😊  Thank you for your work 🙏🏻  I am hoping that I will be able to get the demo running. However, seems like a couple of files missing .  Specifically these 2 files are missing:  
```
~/dist/wa-sqlite-async.mjs
~/dist/wa-sqlite.mjs
~/dist/wa-sqlite-async.wasm
~/dist/wa-sqlite-async.wasm
```
From where can I get those files ? 
In the meantime, I just copied them from : https://rhashimoto.github.io/wa-sqlite/dist/

Also it seems to need CSP settings. `wasm-unsafe-eval`

**Comment by rhashimoto** [comment]
Please read the [Build section of the README](https://github.com/rhashimoto/wa-sqlite#build).

**Comment by jalsco** [comment]
Hi @rhashimoto thanks for your fast reply. And thanks for a wonderful project ! 

Yes I had already read that section of the README.  I am using the "buildless",  with pre-built artifacts.  Are you saying I do not need those files if I do something a certain way ? Could you please elaborate ? 🤷🏻‍♂️

The webpages I am creating  (actually porting existing tools, to web) , are progressing well now.  But I am using the files I mentioned above as having been copied from   the link I gave. IS there another way I should have done it ?

**Comment by rhashimoto** [comment]
Your issue says that files are missing from dist/. They can be found on the "buildless" branch, or you can build them yourself if you are on the "master" branch.

**Comment by jalsco** [comment]
Thanks for the link. When I did the `git clone`  those did not come across. 

Without that link provided (thanks 🙏🏻😊 ), I probably would not have enough knowledge of `git` and/or github to have found them easily. But there they are 😉
